<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div class="panel-heading">
                <a id="logo" href="<?php echo BASE; ?>">
                    <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                </a> <br>
            </div>
            <div class="panel-body">
                <h4 class="alert alert-danger">
                    <i class="fa fa-warning"></i> 
                    O HXPHP 3 só é compatível com o PHP 7
                </h4>
                <p class="alert alert-info">
                    Para continuar usando com o <strong>PHP <?php echo PHP_VERSION; ?></strong> execute o comando abaixo no terminal no diretório escolhido para instalar o <strong>HXPHP 2</strong>:

                    <br> <br>

                    <code>composer create-project --prefer-dist hxphp/hxphp-2 hxphp</code>
                </p>

                <h5 class="alert alert-warning">
                    <i class="fa fa-info"></i>
                    Se você optar por atualizar o PHP lembre-se de atualizar todas as depend&ecirc;ncias atrav&eacute;s do Composer.
                </h5>
            </div>
        </div>
    </div>
</div>
