<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-custom">
      <div class="panel-heading">
        <a id="logo" href="<?php echo BASE; ?>">
          <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
        </a> <br>
        <?php echo (isset($this->menu) ? $this->menu : ''); ?>
      </div>
      <div class="panel-body">
        <form action="/action_page.php">
          <div class="form-group">
            <label for="username">Usuário:</label>
            <input type="text" name="username" class="form-control" id="username">
          </div>
          <div class="form-group">
            <label for="password">Senha:</label>
            <input type="password" name="password" class="form-control" id="password">
          </div>
          <div class="checkbox">
            <label><input type="checkbox"> Lembrar</label>
          </div>
          <button type="submit" class="btn btn-default">Entrar</button>
        </form>
      </div>
    </div>
  </div>
</div>